# nginx proxy address - http://172.17.0.1:8093

name: zulip
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  zulip:
    image: zulip/docker-zulip:latest
    pull_policy: always
    container_name: zulip-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - zulip
    ports:
      - "172.17.0.1:8093:80"
    environment:
      TZ: ${TZ:-America/New_York}
      DB_HOST: zulip-db
      DB_HOST_PORT: 5432
      DB_USER: ${DB_USER_NAME:-zulip}
      SETTING_MEMCACHED_LOCATION: zulip-memcached:11211
      SETTING_RABBITMQ_HOST: zulip-rabbitmq
      SETTING_REDIS_HOST: zulip-redis
      SECRETS_rabbitmq_password: ${RABBITMQ_PASS:-changeme_db_password}
      SECRETS_secret_key: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      SECRETS_postgres_password: ${DB_USER_PASS:-changeme_db_password}
      SECRETS_memcached_password: ${MEMCACHED_PASS:-changeme_db_password}
      SECRETS_redis_password: ${REDIS_PASS:-changeme_db_password}
      SETTING_EXTERNAL_HOST: ${BASE_HOST_NAME:-$HOSTNAME}.${BASE_DOMAIN_NAME:-example.com}
      SETTING_ZULIP_ADMINISTRATOR: ${APP_ADMIN_USER:-admin}@${BASE_DOMAIN_NAME:-example.com}
      SETTING_EMAIL_HOST: ${EMAIL_SERVER_HOST:-172.17.0.1}
      SETTING_EMAIL_HOST_USER: ${EMAIL_SERVER_USER:-}
      SECRETS_email_password: ${EMAIL_SERVER_PASS:-}
      SETTING_EMAIL_PORT: ${EMAIL_SERVER_PORT:-587}
      SETTING_EMAIL_USE_TLS: true
      SETTING_EMAIL_FROM_ADDRESS: ${EMAIL_SERVER_MAIL_FROM:-noreply@example.com}
      ZULIP_AUTH_BACKENDS: EmailAuthBackend
    volumes:
      - ./volumes/data/zulip:/data
    depends_on:
      - zulip-db
      - zulip-redis
      - zulip-memcached
      - zulip-rabbitmq

  zulip-db:
    image: zulip/zulip-postgresql:14
    pull_policy: always
    container_name: zulip-db
    restart: always
    logging: *default-logging
    networks:
      - zulip
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-zulip}
      POSTGRES_USER: ${DB_USER_NAME:-zulip}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./volumes/data/db/postgres/zulip:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  zulip-memcached:
    image: memcached:alpine
    container_name: zulip-memcached
    restart: always
    pull_policy: always
    logging: *default-logging
    networks:
      - zulip

  zulip-redis:
    image: redis:alpine
    container_name: zulip-redis
    restart: always
    pull_policy: always
    logging: *default-logging
    networks:
      - zulip

  zulip-rabbitmq:
    image: rabbitmq:latest
    container_name: zulip-rabbitmq
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-zulip}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-changeme_db_password}
    networks:
      - zulip

networks:
  zulip:
    name: zulip
    external: false
